language: node_js

env:
  SSH_USER: root
  APP_PATH: /root/coffee-print/coffee-print-docker

sudo: false

git:
  depth: false

branches:
  only:
    - master

before_install:
  - openssl aes-256-cbc -K $encrypted_9a7da7495713_key -iv $encrypted_9a7da7495713_iv -in ./.travis/id_rsa.enc -out ./.travis/id_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./.travis/id_rsa
  - echo -e "Host $SSH_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
  - ssh-add ./.travis/id_rsa

install: false

script:
  - echo "npm test temporarily disabled"

deploy:
  provider: script
  skip_cleanup: true
  script: bash -c 'rsync ./{docker-compose.yml,nginx.conf} $SSH_USER@$SSH_HOST:$APP_PATH/
    && ssh root@$SSH_HOST "systemctl restart coffee-print"'
  on:
    branch: master
