language: node_js
env:
  SSH_USER: root
  APP_PATH: /root/coffee-print/coffee-print-docker
  SERVICE_NAME: coffee-print

sudo: false

git:
  depth: false

branches:
  only:
    - master

before_install:
  - openssl aes-256-cbc -K $encrypted_0e3e93ea58cc_key -iv $encrypted_0e3e93ea58cc_iv -in ./.travis/id_rsa.enc -out ./.travis/id_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./.travis/id_rsa
  - echo -e "Host $SSH_HOST\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
  - ssh-add ./.travis/id_rsa

install: true

script:
  - echo "npm test temporarily disabled"

# файл закодированный в openssl в Windows travis не может расшифровать, поэтому
# производим расшифровку на сервере

deploy:
  provider: script
  skip_cleanup: true
  script: bash -c '
    rsync ./{docker-compose.yml,nginx.conf} $SSH_USER@$SSH_HOST:$APP_PATH/
    && ssh $SSH_USER@$SSH_HOST "
      && rm -rf $APP_PATH/.env.enc
      && systemctl restart $SERVICE_NAME"'
  on:
    branch: master
