version: '3.7'
services:
  server:
    image: node:10.16.0
    command: >
      bash -c "
      cd $APP_DIR
      && npm install
      && npm start"
    ports:
      - $APP_PORT:$APP_PORT
    volumes:
       - ./../coffee-print-server:$APP_DIR
    env_file: .env
    depends_on:
      - db

  account-server:
    image: node:10.16.0
    command: >
      bash -c "
      cd $APP_DIR
      && npm install
      && npm start"
    ports:
      - $ACCOUNT_SERVER_PORT:$ACCOUNT_SERVER_PORT
    volumes:
       - ./../coffee-print-account-server:$APP_DIR
    env_file: .env
    depends_on:
      - account-server-db

  db:
    image: postgres:11.4-alpine
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_PORT: $POSTGRES_PORT

  account-server-db:
    image: postgres:11.4-alpine
    ports:
      - 5433:$ACCOUNT_SERVER_POSTGRES_PORT
    volumes:
      - account-server-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $ACCOUNT_SERVER_POSTGRES_USER
      POSTGRES_PASSWORD: $ACCOUNT_SERVER_POSTGRES_PASSWORD
      POSTGRES_DB: $ACCOUNT_SERVER_POSTGRES_DB
      POSTGRES_PORT: $ACCOUNT_SERVER_POSTGRES_PORT

  nginx:
    image: nginx:1.17.1-alpine
    depends_on:
      - server
      - account-server
    volumes:
      - ./../coffee-print-client:/var/www/client
      - ./../coffee-print-account-client:/var/www/account-client
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - 8090:8090
      - 80:80
      - 443:443

volumes:
  postgres:
  account-server-postgres:

