version: '3.7'
services:
  app:
    image: node:11.6.0
    command: >
      bash -c "
      cd $APP_DIR
      && npm install
      && npm start"
    ports:
      - $APP_PORT:$APP_PORT
    volumes:
       - ./../coffee-print-server:$APP_DIR
    env_file: .env
    depends_on:
      - db

  db:
    image: postgres:11.1-alpine
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    volumes:
      - coffee-print-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_PORT: $POSTGRES_PORT

  nginx:
    image: nginx:1.15.8-alpine
    depends_on:
      - app
    volumes:
      - ./../coffee-print-client:/var/www/site
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - 8090:8090
      - 80:80
      - 443:443

volumes:
  coffee-print-postgres:
